name: python-package

on:
  release:
    types: [published]
  workflow_dispatch: null

permissions:
  id-token: write  # Required for trusted publishing

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    environment: package

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install from source
        shell: pwsh
        run: uv pip install --system -e . wheel "setuptools==58.1.0"

      - name: Build 
        shell: pwsh
        run: |
          pip install build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
